---
version: 2
multicolumn: false
web-width: 800px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/Loss_Functions/Figure.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/74776/articles/356680/master/folder/figures/Loss_Functions"
    url: "/users/74776/articles/356680/master/file/figures/Loss_Functions/Figure.png"
