---
version: 2
multicolumn: false
web-width: 600px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/saddle-point/Optimum_Challenges.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/74776/articles/356680/master/folder/figures/saddle-point"
    url: "/users/74776/articles/356680/master/file/figures/saddle-point/Optimum_Challenges.svg"
