---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/ANN_activation/ANN_activation.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/74776/articles/356680/master/file/figures/ANN_activation/ANN_activation.svg"
    folder_url: "/users/74776/articles/356680/master/folder/figures/ANN_activation"
