---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/RNN2/RNN.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/74776/articles/356680/master/folder/figures/RNN2"
    url: "/users/74776/articles/356680/master/file/figures/RNN2/RNN.png"
